#
#   Copyright 2011 Joe Block <jpb@ApesSeekingKnowledge.net>
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#       You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# 
# Example of preconfiguring LDAP settings.
#
# These plists need editing - search for example.com and change
# per your local setup. It's probably less hassle to set it up
# on a workstation then copy the plists from
# /Library/Preferences/DirectoryService, though.

include /usr/local/share/luggage/luggage.make

TITLE=nuke_diginotar_certificate
REVERSE_DOMAIN=net.unixorn
PAYLOAD=pack-script-postflight
